#ifndef __COLOR
#define __COLOR

#define COLOR_LIGHT_BLACK 8 | COLOR_BLACK
#define COLOR_LIGHT_RED 8 | COLOR_RED
#define COLOR_LIGHT_GREEN 8 | COLOR_GREEN
#define COLOR_LIGHT_YELLOW 8 | COLOR_YELLOW
#define COLOR_LIGHT_BLUE 8 | COLOR_BLUE
#define COLOR_LIGHT_MAGENTA 8 | COLOR_MAGENTA
#define COLOR_LIGHT_CYAN 8 | COLOR_CYAN
#define COLOR_LIGHT_WHITE 8 | COLOR_WHITE

#define FCOLOR_BLACK 0X10 | COLOR_BLACK
#define FCOLOR_LIGHT_BLACK 0X10 | COLOR_LIGHT_BLACK
#define FCOLOR_RED 0X10 | COLOR_RED
#define FCOLOR_LIGHT_RED 0X10 | COLOR_LIGHT_RED
#define FCOLOR_GREEN 0X10 | COLOR_GREEN
#define FCOLOR_LIGHT_GREEN 0X10 | COLOR_LIGHT_GREEN
#define FCOLOR_YELLOW 0X10 | COLOR_YELLOW
#define FCOLOR_LIGHT_YELLOW 0X10 | COLOR_LIGHT_YELLOW
#define FCOLOR_BLUE 0X10 | COLOR_BLUE
#define FCOLOR_LIGHT_BLUE 0X10 | COLOR_LIGHT_BLUE
#define FCOLOR_MAGENTA 0X10 | COLOR_MAGENTA
#define FCOLOR_LIGHT_MAGENTA 0X10 | COLOR_LIGHT_MAGENTA
#define FCOLOR_CYAN 0X10 | COLOR_CYAN
#define FCOLOR_LIGHT_CYAN 0X10 | COLOR_LIGHT_CYAN
#define FCOLOR_WHITE 0X10 | COLOR_WHITE
#define FCOLOR_LIGHT_WHITE 0X10 | COLOR_LIGHT_WHITE

#endif